spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ies
    username: root
    password: Mahakal@143
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Choose 'none', 'update', 'create', or 'create-drop' based on your needs
    show-sql: true      # Enables SQL query logging for debugging

  mail:
    host: smtp.gmail.com
    port: 587                      # Commonly used ports: 587 (TLS), 465 (SSL), or 25
    username: krushnakanheibehera@gmail.com    # e.g., example@domain.com
    password: Mahakal@143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

